#ifndef _PORT_H
#define _PORT_H

#include "app/inc/component_id.h"
#include "driver/gpio/gpio.h"

#define HEARTBEAT_LED_PORT (GPIO_PORTC)
#define HEARTBEAT_LED_PIN (GPIO_PIN0)
#define HEARTBEAT_LED_INIT_STATE (GPIO_HIGH)

#define HEARTBEAT2_LED_PORT (GPIO_PORTC)
#define HEARTBEAT2_LED_PIN (GPIO_PIN1)
#define HEARTBEAT2_LED_INIT_STATE (GPIO_HIGH)

#define KEYPAD_COL_0_PORT (GPIO_PORTA)
#define KEYPAD_COL_0_PIN (GPIO_PIN2)
#define KEYPAD_COL_1_PORT (GPIO_PORTA)
#define KEYPAD_COL_1_PIN (GPIO_PIN3)
#define KEYPAD_COL_2_PORT (GPIO_PORTA)
#define KEYPAD_COL_2_PIN (GPIO_PIN4)
#define KEYPAD_COL_3_PORT (GPIO_PORTA)
#define KEYPAD_COL_3_PIN (GPIO_PIN5)

#define KEYPAD_ROW_0_PORT (GPIO_PORTB)
#define KEYPAD_ROW_0_PIN (GPIO_PIN0)
#define KEYPAD_ROW_1_PORT (GPIO_PORTB)
#define KEYPAD_ROW_1_PIN (GPIO_PIN1)
#define KEYPAD_ROW_2_PORT (GPIO_PORTB)
#define KEYPAD_ROW_2_PIN (GPIO_PIN2)
#define KEYPAD_ROW_3_PORT (GPIO_PORTB)
#define KEYPAD_ROW_3_PIN (GPIO_PIN3)

#endif
