
#ifndef CONFIG_H_
#define CONFIG_H_

#include "app/inc/component_id.h"

// TODO: should be auto defined depending on the selected mcu
#define STRUCT_USE_SDS (0)
#define ADC_READING_METHOD1 (1)
#define INTERNAL_EEPROM (1)
#define USE_EEPROM (0)
#define USE_WDT (1)
#define USE_VLTD (1)
#define BUZZER_USED	(1)

#define SAMPLE_SLAVE_ADDRESS (0x5C)

#define SW_TOUCH_BS14_2_MCU (0)   //using simple communication
#define SW_TOUCH_BS13_2_MCU (1)   //like gpio
#define SW_TOUCH_ROHM (0)         //I2C

#define APP_SYS_HEALTH (1)
#define APP_USE_HEARTBEAT (1)
#define HEARTBEAT_EXECUTION_PRINT_ENABLED (1)
#define HEARTBEAT_OVERRUN_FLAG_PRINT_ENABLED (1)
#define APP_USE_WDT (1)

#if USE_EEPROM == 1
#define APP_EEPROM_ACCESS_ENABLED (1)
#define EXTERNAL_EEPROM_USED (1)
#else
#define APP_EEPROM_ACCESS_ENABLED (0)
#define EXTERNAL_EEPROM_USED (0)
#endif

#define ERROR_ENABLE 0

// NOTE: THE DELAY FOR THE RUNTIME TASK SHOULD BE HIGHER ENOUGH THAT IF IT DEPENDS ON A COMPONENT IT IS FOR SURE THAT THE COMPONENT VALUE HAS BEEN ACQUIRED.
#define APP_RUN_TIME_TASK_DELAY 100
#define APP_RUN_TIME_TASK_UPDATE_PERIOD_MS 100
#define APP_STARTUP_DELAY_PERIOD_MS 5000
#define APP_RUNNING_TICK (5)

#define OS_LOG_MAIN_BUFFER_SIZE (300)
#define OS_LOG_USER_LOGS_NUM (5)
//#define OS_LOG_DISPLAY_SIZE (200)
#define OS_LOG_USE_PRINTF (1)

#define OS_SCHEDULER_USER_TASKS_NUM 15
#define OS_SCHEDULER_SYSTEM_TASKS_NUM 3
#define OS_RUN_TIME_USER_HOOKS_NUM 1

#define OS_TICK_PERIOD_MS (1)
#define WDT_UPDATE_PERIOD_MS (OS_TICK_PERIOD_MS)
#define OS_TIMER_UPDATE_PERIOD_MS (10)
#define UART_UPDATE_PERIOD_MS (5)
#define SW_UART_UPDATE_PERIOD (5)
#define ADC_UPDATE_PERIOD_MS (10)
#define HEARTBEAT_UPDATE_PERIOD_MS (500)
#define FINPUT_MODULE_UPDATE_PERIOD_MS (10)
#define FOUTPUT_MODULE_UPDATE_PERIOD_MS (10)
#define DINPUT_MODULE_UPDATE_PERIOD_MS (5)
#define DOUTPUT_MODULE_UPDATE_PERIOD_MS (10)
#define AINPUT_MODULE_UPDATE_PERIOD_MS (10)
#define KEYPAD_UPDATE_PERIOD_MS (5)   // NOTE: 4x4, total of 20msec
#define SSD_UPDATE_PERIOD_MS (5)
#define LED_MATRIX_UPDATE_PERIOD_MS (5)
#define DISPLAY_MATRIX_UPDATE_PERIOD_MS (5)
#define MOTOR_COM_UPDATE_PERIOD_MS (20)
#define APP_MOTOR_COM_UPDATE_PERIOD_MS (20)
#define EEPROM_UPDATE_PERIOD_MS (10)
#define TEST_MODE_UPDATE_PERIOD_MS (100)
#define DINPUT_LOCK_SENSOR_UPDATE_PERIOD (500)
#define FINPUT_DRAIN_VALVE_SENSOR_UPDATE_PERIOD (500)
#define AINPUT_WATER_LEVEL_SENSOR_UPDATE_PERIOD (500)
#define APP_WATER_LEVEL_SENSOR_UPDATE_PERIOD (100)   // FOR SOME REASON IT RESETS IF SET TO 500
#define APP_BUZZER_UPDATE_PERIOD (10)
#define APP_LID_LOCK_UPDATE_PERIOD_MS (10)
#define APP_DRAIN_VALVE_UPDATE_PERIOD_MS (10)
#define APP_SW_UPDATE_PERIOD_MS (5)
#define APP_WASHER_UPDATE_PERIOD_MS (100)
#define APP_ERROR_HANDLING_UPDATE_PERIOD (10)
#define APP_FILL_UPDATE_PERIOD (100)
#define DISP_UPDATE_PERIOD_MS (100)
#define APP_MW_SYSTEM_UPDATE_PERIOD_MS (100)

#define UART_RX_INT 1
#define UART_RECV_BUFFER_SIZE (300)
#define UART_TRANS_BUFFER_SIZE (300)
#define DEBUG_PORT_ID UART_0
#define MOTOR_COM_PORT_ID UART_2

#define STWI_USED (1)
#define EEPROM_BUFFER_SIZE (150)

#define WDT_RESET_MSEC (WDT_DETECT_TIME_EXP_21)   //reset time according to datasheet and clock setting = 26msec

#define ADC_RAMPUP_DELAY_PERIOD_MS (1000)   // to avoid the wrong data readings from a cold start

// LOG: mine
// #define DINPUT_MODULE_PRESSED_LEVEL 0
// #define DINPUT_MODULE_RELEASED_LEVEL 1
//#define TACTILE 0
#define IC_813 1

#if TACTILE
#define DINPUT_MODULE_PRESSED_LEVEL 1
#define DINPUT_MODULE_RELEASED_LEVEL 0
#elif IC_813
#define DINPUT_MODULE_PRESSED_LEVEL 0
#define DINPUT_MODULE_RELEASED_LEVEL 1
#endif
#define DOUTPUT_MODULE_LOW_LEVEL 0
#define DOUTPUT_MODULE_HIGH_LEVEL 1

//LOG: mine
// #define SSD_COM_ANODE 0
// #define SSD_COM_CATHODE 1
#define SSD_COM_ANODE 1
#define SSD_COM_CATHODE 0
#define SSD_ON (0)
#define SSD_OFF (1)

#define LED_MATRIX_COL_NUMBER (2)
#define LED_MATRIX_ROW_NUMBER (8)
#define LED_MATRIX_ON (1)
#define LED_MATRIX_OFF (0)
//LOG: mine
// #define LED_MATRIX_ALL_OFF (0xFF)
#define LED_MATRIX_ALL_OFF (0x00)

#define KEYPAD_COL_NUMBER (3)
#define KEYPAD_ROW_NUMBER (2)
#define KEYPAD_PRESSED_LEVEL (1)
#define KEYPAD_RELEASED_LEVEL (0)

#define DISPLAY_MATRIX_COL_NUMBER (LED_MATRIX_COL_NUMBER)
#define DISPLAY_MATRIX_ROW_NUMBER (LED_MATRIX_ROW_NUMBER)

#define SSD_DIGITS_NUMBER (SSD_DIGITS_NUM)
#define DOUTPUT_MODULES_NUM (DOUTPUT_DEVICES_NUM)
#define AINPUT_MODULES_NUM (AINPUT_DEVICES_NUM)
#define FINPUT_MODULES_NUM (FINPUT_DEVCIES_NUM)
#define FOUTPUT_MODULES_NUM (FOUTPUT_DEVCIES_NUM)
#define DINPUT_MODULES_NUM (DINPUT_DEVICES_NUM)
#define ADC_CHANNELS_NO (AINPUT_DEVICES_NUM)
#define OS_TIMERS_NUM (OS_TIMERS_NUM)
#define UART_INTERFACES_NUM (2)



#endif   // CONFIG_H_
